target 'AXCGiphy' do
  pod "Giphy-iOS", :path => "../"
  pod 'AFNetworking/Serialization', '~> 2.3.1'
  pod 'AnimatedGIFImageSerialization', '~> 0.2.0'
end

target 'Tests' do
  pod "Giphy-iOS", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
